platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :deploy_to_testflight do |options|
    # Your existing API key setup
    api_key = app_store_connect_api_key(
      key_id: "9N2PC3WPXC",
      issuer_id: "c3e455d1-3203-4ed7-8a3e-a2095344f155",
      key_filepath: "../AuthKey_9N2PC3WPXC.p8",
      in_house: false
    )

    # Increment build number
    increment_build_number({
      build_number: latest_testflight_build_number + 1
    })

    # Specify the Xcode version
    xcversion(version: "15.3")

    # Update code signing settings before building
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "Runner.xcodeproj",
      team_id: "NHF49WV7N9",
      bundle_identifier: "com.deloy.cicdapp",
      code_sign_identity: "iPhone Distribution",
      profile_name: "CINEW",
    )

    # Build your app with specific export options
    gym(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      clean: true,
      export_options: {
        method: "app-store",
        provisioningProfiles: {
          "com.deloy.cicdapp": "CINEW"
        }
      }
    )

    # Optionally revert to automatic signing after build
    update_code_signing_settings(
      use_automatic_signing: true,
      path: "Runner.xcodeproj",
      team_id: "NHF49WV7N9",
      bundle_identifier: "com.deloy.cicdapp",
      code_sign_identity: "iPhone Distribution",
      profile_name: "CINEW",
    )

    # Upload to TestFlight
    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true,
      changelog: "jojfsodjfiosjojakkjfdopa",
    )
  end
end
