name: Deploy Flutter App to TestFlight

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Install Fastlane
        run: gem install fastlane -N --user-install

      - name: Install cocoapods
        run: sudo gem install cocoapods

      - name: Build and Upload to Testflight
        env:
          API_KEY_PATH: ../auth_key.p8
        run: |
          cd ios
          echo $(pwd)
          pod install
          fastlane deploy_to_testflight