name: Deploy Flutter App to TestFlight

on:
  push:
    branches:
      - main
      - develop

jobs:
  IOS_BUILD_AND_DISTRIBUTE:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy Apple credentials content from local file
        run: |
          cp  ${{ github.workspace }}/AuthKey_9N2PC3WPXC.p8 ${{ github.workspace }}/auth_key.p8

      - name: Install apple certificate
        uses: apple-actions/import-codesign-certs@v2
        with:
          p12-file-path: ${{ github.workspace }}/CertificatesCICD.p12
          p12-password: 123456

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.9"

      - name: Clean and install dependencies
        run: |
          flutter clean
          flutter pub get

      - name: Install Fastlane
        run: gem install fastlane -N --user-install

      - name: Install Cocoapods
        run: sudo gem install cocoapods

      - name: Build and upload to TestFlight
        env:
          API_KEY_PATH: ${{ github.workspace }}/AuthKey_9N2PC3WPXC.p8
        run: |
          cd ios
          pod install
          fastlane deploy_to_testflight
