name: Deploy Flutter App to TestFlight

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          rubygems: latest
          working-directory: ios
          bundler-cache: true  # This automatically runs `bundle install`

      - name: bundle install
        run: bundle install

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Prepare for iOS build
        run: bundle exec fastlane deploy_to_testflight
        env:
          API_KEY_PATH: ${{ github.workspace }}/ios/auth_key.p8
